services:
  nginx:
    image: nginx:1.29-alpine-slim
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    networks:
      - rdb2025
      - payment-processor
    container_name: rdb2025-nginx
    depends_on:
      - go1
      - go2
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"

  go1: &go1
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    container_name: go1
    hostname: go1
    networks:
      - rdb2025
      - payment-processor
    environment:
     - REDIS_URL=redis:6379
     - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
     - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=rdb2025
     - POSTGRES_HOST=pg
     - POSTGRES_PORT=5432
    depends_on:
      redis:
        condition: service_started
      pg:
        condition: service_healthy
    #restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "60MB"
  go2:
    <<: *go1
    container_name: go2
    hostname: go2

  redis:
    image: redis:7-alpine
    container_name: rdb2025-redis
    command: redis-server --appendonly no --maxclients 20000
    networks:
      - rdb2025
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "80MB"

  pg:
    image: postgres:17-alpine
    hostname: pg
    container_name: rdb2025-postgres
    volumes:
      - ./docker/pg/rinha.sql:/docker-entrypoint-initdb.d/rinha.sql
    ports:
      - "5432:5432"
    networks:
      - rdb2025
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rdb2025
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rdb2025"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "135MB"

networks:
  payment-processor:
    name: payment-processor
    external: true
  rdb2025:
    driver: bridge

